Made PnP More Robust
personalrobotics/face_detection pull request #4
Opened 2022-03-02 02:45 UTC by amalnanavati

See https://github.com/personalrobotics/ada_feeding/issues/11 for details. 

Basically, PnPRansac was extremely unstable, and perceiving faces in strange and varying orientations. This is likely because we only use 12 points to align the face, and Ransac randomly subsamples from them. Ransac works well with many points; 12 seems too low. (Note that PnPRansac was first introduced in [this commit](https://github.com/personalrobotics/face_detection/commit/281d5b002e4fb4ea3c47cd757b43e171e838ab86), and I couldn't find documentation as to why.)

This commit reverts PnPRansac to PnP. To further increase stability, it initializes PnP with the output of the previous PnP call.

2022-03-02 23:58 UTC, egordon-HRI requested changes
Thanks for catching this! Very much a change from before my time that I just kinda accepted implicitly.

Is `bool solvedPnP` meant to do anything? It is unused unless I'm missing something. Please remove if it is vestigial.

Alternatively, I can't actually see where you change to have PnP initialized with the previous iteration. Maybe that is what's missing right now.

2022-03-03 00:08 UTC, egordon requested changes
Apologies, posted from my work account, consider this the true review.

2022-03-03 02:01 UTC, amalnanavati commented
`solvedPnP` is used in line 154, which is what enables it to get initialized. Specifically, the parameter that is passed to `solvePnP(...)` after the translation vector is a [bool that specifies whether to use the values already in the rotation/translation vector as an initialization or not](https://docs.opencv.org/3.4/d9/d0c/group__calib3d.html#ga549c2075fac14829ff4a58bc931c033d). The first iteration, it is false. On every subsequent iteration, it initializes solvePnP with the previous solution.

2022-03-03 04:26 UTC, egordon approved these changes
Makes sense, then LGTM.

Only thing I would consider is to reset `solvedPnP` to false when we are commanded to stop face tracking (i.e. when the robot moves away from the face). But nbd.

2022-03-03 19:57 UTC, amalnanavati commented
Done. I'll test this new change on the robot first before merging it in.

2022-03-03 22:51 UTC, amalnanavati commented
Works on the robot

2022-03-03 22:51 UTC, merged